# ArgoCD self-managed configuration for dev cluster

argo-cd:
  # Add labels for Backstage Kubernetes plugin discovery
  global:
    labels:
      backstage.io/kubernetes-id: argocd
    podLabels:
      backstage.io/kubernetes-id: argocd

  server:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
    podLabels:
      backstage.io/kubernetes-id: argocd

  controller:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podLabels:
      backstage.io/kubernetes-id: argocd

  repoServer:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
    podLabels:
      backstage.io/kubernetes-id: argocd

  applicationSet:
    enabled: true
    replicas: 1
    podLabels:
      backstage.io/kubernetes-id: argocd

  redis:
    enabled: true

  configs:
    cm:
      statusbadge.enabled: "true"
      timeout.reconciliation: 60s

application:
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
      description: "ArgoCD GitOps Controller (self-managed)"
  spec:
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
