apiVersion: v2
name: backstage
description: Helm chart for deploying Backstage Developer Portal with K8s, ArgoCD, and Airflow integrations
type: application
version: 1.0.0
appVersion: "1.30.0"
dependencies:
  - name: backstage
    version: "2.5.0"
    repository: "https://backstage.github.io/charts"
  - name: global-templates
    version: "1.12.*"
    repository: "file://../global-templates"
    import-values:
      - defaults
