apiVersion: v2
name: airflow-operator
description: Helm chart for deploying Apache Airflow Operator (airflow-helm/airflow)
type: application
version: 1.0.0
appVersion: "8.9.0"
dependencies:
  - name: airflow
    version: "8.9.0"
    repository: "https://airflow-helm.github.io/charts"
