# Airflow Operator deployment for dev cluster
# MINIMAL config for low-memory environments (Kind/local)

airflow:
  # Airflow core configuration
  airflow:
    # LocalExecutor = no workers, no Redis needed (saves ~500MB+)
    executor: LocalExecutor

    image:
      repository: apache/airflow
      tag: 2.8.1-python3.11
      pullPolicy: IfNotPresent

    # Development-friendly configuration
    config:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"

    # Default admin user
    users:
      - username: admin
        password: admin
        role: Admin
        email: admin@example.com
        firstName: Admin
        lastName: User

  # Web UI - minimal resources
  web:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    service:
      type: ClusterIP
      port: 8080

  # Scheduler - minimal resources
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Celery workers - DISABLED for LocalExecutor
  workers:
    enabled: false

  # Triggerer - DISABLED to save resources
  triggerer:
    enabled: false

  # Database - PostgreSQL with minimal resources
  postgresql:
    enabled: true
    auth:
      postgresPassword: airflow-dev
      username: airflow
      password: airflow-dev
      database: airflow
    primary:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      persistence:
        enabled: false # Disable persistence for dev

  # Redis - DISABLED (not needed for LocalExecutor)
  redis:
    enabled: false

  # DAG sync - disabled, mount DAGs directly or use configmaps
  dags:
    gitSync:
      enabled: false

  # Logs
  logs:
    persistence:
      enabled: false

  # Flower disabled
  flower:
    enabled: false

# ArgoCD application overrides
application:
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-5"
      description: "Apache Airflow (minimal) - DAG orchestration platform"
  spec:
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
